# Import libraries

In [1]:
import pandas as pd
import numpy as np
import os
import ast

In [2]:
movies=pd.read_csv('movies.csv')
credits=pd.read_csv('credits.csv')

In [3]:
movies.head(1)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity                               production_companies  \
0  150.437577  [{"name": "Ingenious Film Partners", "id": 289...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                       tagline   title  vote_average  vote_count  
0  Enter the World of Pandora.  Avatar           7.2       11800

In [4]:
#Details of all the cast of all the actors who acted in that movie

credits.head(1)['cast'].values



array(['[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "ge

In [5]:
#Details of all the crew of all the actors who acted in that movie

credits.head(1)['crew'].values



array(['[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cam

### Merge the two dataframes

In [6]:
movies=movies.merge(credits,on='title')

In [7]:
movies.shape

(4809, 23)

In [8]:
movies.head(1)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity                               production_companies  ... runtime  \
0  150.437577  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                       tagline   title vote_average vote_count movie_id  \
0  Enter the World of Pandora.  Avatar          7.2      11800    19995   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  

[1 rows x 23 columns]

### Drop the unnecessary columns

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4809 non-null   int64  
 1   genres                4809 non-null   object 
 2   homepage              1713 non-null   object 
 3   id                    4809 non-null   int64  
 4   keywords              4809 non-null   object 
 5   original_language     4809 non-null   object 
 6   original_title        4809 non-null   object 
 7   overview              4806 non-null   object 
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object 
 10  production_countries  4809 non-null   object 
 11  release_date          4808 non-null   object 
 12  revenue               4809 non-null   int64  
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object 
 15  status               

In [10]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]


In [11]:
movies.isnull.sum()

#it means that it will give the total number of such movies where we will have columns such that those fileds are NULLs.

AttributeError: 'function' object has no attribute 'sum'

In [12]:
movies.dropna(inplace=True)
#drop those rows where this was false

In [13]:
# WIll give the number of rows which are duplicated
movies.duplicated().sum()


0

In [14]:
print(movies.iloc[0].genres)

[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]


### Convert Function

In [15]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):  #ast library will do exactly this. it will convert the string to the list of dictonaries.
        L.append(i['name']) 
    return L 

In [16]:

#This could have been used, unfortunately thr genres thing is encoded inside a string and is NOT A LIST.
def get_tags(x):
    lists=[]
    for y in x:
           lists.append(y["name"])
    return lists

movies['genre']=movies['genres'].apply(lambda x:convert(x))

In [17]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  \
0  [{"credit_id": "52fe48009251416c750aca23", "de...   
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...   
2  [{"credit_id": "54805967c3a36829b5002c41", "de...   
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...   
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...   

                                           genre  
0  [Action, Adventure, Fantasy, Science Fiction]  
1                   [Adventure, Fantasy, Action]  
2                     [Action, Adventure, Crime]  
3               [Action, Crime, Drama, Thriller]  
4           [Action, Adventure, Science Fiction]

### Dropping the genres column

In [18]:
movies.drop(columns=['genres'])

movie_id                                     title  \
0        19995                                    Avatar   
1          285  Pirates of the Caribbean: At World's End   
2       206647                                   Spectre   
3        49026                     The Dark Knight Rises   
4        49529                               John Carter   
...        ...                                       ...   
4804      9367                               El Mariachi   
4805     72766                                 Newlyweds   
4806    231617                 Signed, Sealed, Delivered   
4807    126186                          Shanghai Calling   
4808     25975                         My Date with Drew   

                                               overview  \
0     In the 22nd century, a paraplegic Marine is di...   
1     Captain Barbossa, long believed to be dead, ha...   
2     A cryptic message from Bond’s past sends him o...   
3     Following the death of District Attorney Harve...   
4     John Carter is a war-weary, former military ca...   
...                                                 ...   
4804  El Mariachi just wants to play his guitar and ...   
4805  A newlywed couple's honeymoon is upended by th...   
4806  "Signed, Sealed, Delivered" introduces a dedic...   
4807  When ambitious New York attorney Sam is sent t...   
4808  Ever since the second grade when he first saw ...   

                                               keywords  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4     [{"id": 818, "name": "based on novel"}, {"id":...   
...                                                 ...   
4804  [{"id": 5616, "name": "united states\u2013mexi...   
4805                                                 []   
4806  [{"id": 248, "name": "date"}, {"id": 699, "nam...   
4807                                                 []   
4808  [{"id": 1523, "name": "obsession"}, {"id": 224...   

                                                   cast  \
0     [{"cast_id": 242, "character": "Jake Sully", "...   
1     [{"cast_id": 4, "character": "Captain Jack Spa...   
2     [{"cast_id": 1, "character": "James Bond", "cr...   
3     [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4     [{"cast_id": 5, "character": "John Carter", "c...   
...                                                 ...   
4804  [{"cast_id": 1, "character": "El Mariachi", "c...   
4805  [{"cast_id": 1, "character": "Buzzy", "credit_...   
4806  [{"cast_id": 8, "character": "Oliver O\u2019To...   
4807  [{"cast_id": 3, "character": "Sam", "credit_id...   
4808  [{"cast_id": 3, "character": "Herself", "credi...   

                                                   crew  \
0     [{"credit_id": "52fe48009251416c750aca23", "de...   
1     [{"credit_id": "52fe4232c3a36847f800b579", "de...   
2     [{"credit_id": "54805967c3a36829b5002c41", "de...   
3     [{"credit_id": "52fe4781c3a36847f81398c3", "de...   
4     [{"credit_id": "52fe479ac3a36847f813eaa3", "de...   
...                                                 ...   
4804  [{"credit_id": "52fe44eec3a36847f80b280b", "de...   
4805  [{"credit_id": "52fe487dc3a368484e0fb013", "de...   
4806  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...   
4807  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...   
4808  [{"credit_id": "58ce021b9251415a390165d9", "de...   

                                              genre  
0     [Action, Adventure, Fantasy, Science Fiction]  
1                      [Adventure, Fantasy, Action]  
2                        [Action, Adventure, Crime]  
3                  [Action, Crime, Drama, Thriller]  
4              [Action, Adventure, Science Fiction]  
...                                             ...  
4804                      [Action, Crime, Thriller]  
4805             

In [19]:
movies['keywords'] = movies['keywords'].apply(lambda x:convert(x))

In [20]:
movies.head(6)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   
5       559                              Spider-Man 3   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   
5  The seemingly invincible Spider-Man goes up ag...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
5  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   
5  [dual identity, amnesia, sandstorm, love of on...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   
5  [{"cast_id": 30, "character": "Peter Parker / ...   

                                                crew  \
0  [{"credit_id": "52fe48009251416c750aca23", "de...   
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...   
2  [{"credit_id": "54805967c3a36829b5002c41", "de...   
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...   
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...   
5  [{"credit_id": "52fe4252c3a36847f80151a5", "de...   

                                           genre  
0  [Action, Adventure, Fantasy, Science Fiction]  
1                   [Adventure, Fantasy, Action]  
2                     [Action, Adventure, Crime]  
3               [Action, Crime, Drama, Thriller]  
4           [Action, Adventure, Science Fiction]  
5                   [Fantasy, Action, Adventure]

### Get only the first three Cast Names

In [21]:
def get_first_three_cast_names(text):
    L = []
    for index,i in enumerate(ast.literal_eval(text)):  #ast library will do exactly this. it will convert the string to the list of dictonaries.
        if index==3:
            break
        L.append(i['name']) 
    return L 



In [22]:
movies['cast']=movies['cast'].apply(lambda x:get_first_three_cast_names(x))

In [23]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                               cast  \
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   
1     [Johnny Depp, Orlando Bloom, Keira Knightley]   
2      [Daniel Craig, Christoph Waltz, Léa Seydoux]   
3      [Christian Bale, Michael Caine, Gary Oldman]   
4    [Taylor Kitsch, Lynn Collins, Samantha Morton]   

                                                crew  \
0  [{"credit_id": "52fe48009251416c750aca23", "de...   
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...   
2  [{"credit_id": "54805967c3a36829b5002c41", "de...   
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...   
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...   

                                           genre  
0  [Action, Adventure, Fantasy, Science Fiction]  
1                   [Adventure, Fantasy, Action]  
2                     [Action, Adventure, Crime]  
3               [Action, Crime, Drama, Thriller]  
4           [Action, Adventure, Science Fiction]

### Get only the director from the crew

In [24]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):# use ast again,coz those in string and we want the list inside of it.
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L 



In [25]:
movies['crew']=movies['crew'].apply(lambda x:fetch_director(x))

In [26]:
movies.head(3)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   

                                               cast              crew  \
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   [James Cameron]   
1     [Johnny Depp, Orlando Bloom, Keira Knightley]  [Gore Verbinski]   
2      [Daniel Craig, Christoph Waltz, Léa Seydoux]      [Sam Mendes]   

                                           genre  
0  [Action, Adventure, Fantasy, Science Fiction]  
1                   [Adventure, Fantasy, Action]  
2                     [Action, Adventure, Crime]

### Drop the original genres column

In [27]:
movies.drop(columns=['genres'])

movie_id                                     title  \
0        19995                                    Avatar   
1          285  Pirates of the Caribbean: At World's End   
2       206647                                   Spectre   
3        49026                     The Dark Knight Rises   
4        49529                               John Carter   
...        ...                                       ...   
4804      9367                               El Mariachi   
4805     72766                                 Newlyweds   
4806    231617                 Signed, Sealed, Delivered   
4807    126186                          Shanghai Calling   
4808     25975                         My Date with Drew   

                                               overview  \
0     In the 22nd century, a paraplegic Marine is di...   
1     Captain Barbossa, long believed to be dead, ha...   
2     A cryptic message from Bond’s past sends him o...   
3     Following the death of District Attorney Harve...   
4     John Carter is a war-weary, former military ca...   
...                                                 ...   
4804  El Mariachi just wants to play his guitar and ...   
4805  A newlywed couple's honeymoon is upended by th...   
4806  "Signed, Sealed, Delivered" introduces a dedic...   
4807  When ambitious New York attorney Sam is sent t...   
4808  Ever since the second grade when he first saw ...   

                                               keywords  \
0     [culture clash, future, space war, space colon...   
1     [ocean, drug abuse, exotic island, east india ...   
2     [spy, based on novel, secret agent, sequel, mi...   
3     [dc comics, crime fighter, terrorist, secret i...   
4     [based on novel, mars, medallion, space travel...   
...                                                 ...   
4804  [united states–mexico barrier, legs, arms, pap...   
4805                                                 []   
4806  [date, love at first sight, narration, investi...   
4807                                                 []   
4808          [obsession, camcorder, crush, dream girl]   

                                                   cast                 crew  \
0      [Sam Worthington, Zoe Saldana, Sigourney Weaver]      [James Cameron]   
1         [Johnny Depp, Orlando Bloom, Keira Knightley]     [Gore Verbinski]   
2          [Daniel Craig, Christoph Waltz, Léa Seydoux]         [Sam Mendes]   
3          [Christian Bale, Michael Caine, Gary Oldman]  [Christopher Nolan]   
4        [Taylor Kitsch, Lynn Collins, Samantha Morton]     [Andrew Stanton]   
...                                                 ...                  ...   
4804  [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...   [Robert Rodriguez]   
4805       [Edward Burns, Kerry Bishé, Marsha Dietlein]       [Edward Burns]   
4806         [Eric Mabius, Kristin Booth, Crystal Lowe]        [Scott Smith]   
4807          [Daniel Henney, Eliza Coupe, Bill Paxton]        [Daniel Hsia]   
4808  [Drew Barrymore, Brian Herzlinger, Corey Feldman]   [Brian Herzlinger]   

                                              genre  
0     [Action, Adventure, Fantasy, Science Fiction]  
1                      [Adventure, Fantasy, Action]  
2                        [Action, Adventure, Crime]  
3                  [Action, Crime, Drama, Thriller]  
4              [Action, Adventure, Science Fiction]  
...                                             ...  
4804                      [Action, Crime, Thriller]  
4805                              [Comedy, Romance]  
4806             [Comedy, Drama, Romance, TV Movie]  
4807                                             []  
4808                                  [Documentary]  

[4806 rows x 7 columns]

In [28]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [29]:
movies.head(6)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   
5       559                              Spider-Man 3   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   
3  [Following, the, death, of, District, Attorney...   
4  [John, Carter, is, a, war-weary,, former, mili...   
5  [The, seemingly, invincible, Spider-Man, goes,...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
5  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   
5  [dual identity, amnesia, sandstorm, love of on...   

                                               cast                 crew  \
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]      [James Cameron]   
1     [Johnny Depp, Orlando Bloom, Keira Knightley]     [Gore Verbinski]   
2      [Daniel Craig, Christoph Waltz, Léa Seydoux]         [Sam Mendes]   
3      [Christian Bale, Michael Caine, Gary Oldman]  [Christopher Nolan]   
4    [Taylor Kitsch, Lynn Collins, Samantha Morton]     [Andrew Stanton]   
5      [Tobey Maguire, Kirsten Dunst, James Franco]          [Sam Raimi]   

                                           genre  
0  [Action, Adventure, Fantasy, Science Fiction]  
1                   [Adventure, Fantasy, Action]  
2                     [Action, Adventure, Crime]  
3               [Action, Crime, Drama, Thriller]  
4           [Action, Adventure, Science Fiction]  
5                   [Fantasy, Action, Adventure]

In [30]:
movies.iloc[1].overview

['Captain',
 'Barbossa,',
 'long',
 'believed',
 'to',
 'be',
 'dead,',
 'has',
 'come',
 'back',
 'to',
 'life',
 'and',
 'is',
 'headed',
 'to',
 'the',
 'edge',
 'of',
 'the',
 'Earth',
 'with',
 'Will',
 'Turner',
 'and',
 'Elizabeth',
 'Swann.',
 'But',
 'nothing',
 'is',
 'quite',
 'as',
 'it',
 'seems.']

## Remove the empty space and combine them

In [31]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [32]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [33]:
movies=movies.drop(columns=['genres'])

In [34]:
movies.head(5)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   
3  [Following, the, death, of, District, Attorney...   
4  [John, Carter, is, a, war-weary,, former, mili...   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   
2  [spy, basedonnovel, secretagent, sequel, mi6, ...   
3  [dccomics, crimefighter, terrorist, secretiden...   
4  [basedonnovel, mars, medallion, spacetravel, p...   

                                            cast                crew  \
0  [SamWorthington, ZoeSaldana, SigourneyWeaver]      [JamesCameron]   
1     [JohnnyDepp, OrlandoBloom, KeiraKnightley]     [GoreVerbinski]   
2      [DanielCraig, ChristophWaltz, LéaSeydoux]         [SamMendes]   
3      [ChristianBale, MichaelCaine, GaryOldman]  [ChristopherNolan]   
4    [TaylorKitsch, LynnCollins, SamanthaMorton]     [AndrewStanton]   

                                           genre  
0  [Action, Adventure, Fantasy, Science Fiction]  
1                   [Adventure, Fantasy, Action]  
2                     [Action, Adventure, Crime]  
3               [Action, Crime, Drama, Thriller]  
4           [Action, Adventure, Science Fiction]

In [35]:
movies['tags'] = movies['overview'] + movies['genre'] + movies['keywords'] + movies['cast'] + movies['crew']

In [36]:
movies.head(2)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   

                                            cast             crew  \
0  [SamWorthington, ZoeSaldana, SigourneyWeaver]   [JamesCameron]   
1     [JohnnyDepp, OrlandoBloom, KeiraKnightley]  [GoreVerbinski]   

                                           genre  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   

                                                tags  
0  [In, the, 22nd, century,, a, paraplegic, Marin...  
1  [Captain, Barbossa,, long, believed, to, be, d...

In [37]:
new=movies[['movie_id','title','tags']]

In [38]:
new.head(2)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                                tags  
0  [In, the, 22nd, century,, a, paraplegic, Marin...  
1  [Captain, Barbossa,, long, believed, to, be, d...

In [39]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))

C:\Users\Newtan\AppData\Local\Temp/ipykernel_8252/744744204.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['tags'] = new['tags'].apply(lambda x: " ".join(x))


In [40]:
new.head(11)

movie_id                                     title  \
0      19995                                    Avatar   
1        285  Pirates of the Caribbean: At World's End   
2     206647                                   Spectre   
3      49026                     The Dark Knight Rises   
4      49529                               John Carter   
5        559                              Spider-Man 3   
6      38757                                   Tangled   
7      99861                   Avengers: Age of Ultron   
8        767    Harry Potter and the Half-Blood Prince   
9     209112        Batman v Superman: Dawn of Justice   
10      1452                          Superman Returns   

                                                 tags  
0   In the 22nd century, a paraplegic Marine is di...  
1   Captain Barbossa, long believed to be dead, ha...  
2   A cryptic message from Bond’s past sends him o...  
3   Following the death of District Attorney Harve...  
4   John Carter is a war-weary, former military ca...  
5   The seemingly invincible Spider-Man goes up ag...  
6   When the kingdom's most wanted-and most charmi...  
7   When Tony Stark tries to jumpstart a dormant p...  
8   As Harry begins his sixth year at Hogwarts, he...  
9   Fearing the actions of a god-like Super Hero l...  
10  Superman returns to discover his 5-year absenc...

In [41]:
new.iloc[0]['tags']

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

### Convert the tags to lowercse

In [42]:
new['tags']=new['tags'].apply(lambda x:x.lower())

C:\Users\Newtan\AppData\Local\Temp/ipykernel_8252/3373542102.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['tags']=new['tags'].apply(lambda x:x.lower())


# Import sklearn library

In [43]:

from sklearn.feature_extraction.text import CountVectorizer


In [44]:
cv = CountVectorizer(max_features=5000,stop_words='english') 
#we only select the top 5000 words 
# ignore the english stop worrds like are,is,the etc.

In [45]:
print( cv.fit_transform(new['tags']).toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [46]:
vectors=cv.fit_transform(new['tags']).toarray()

In [48]:
vectors.shape

(4806, 5000)

## Getting the top most feature names

In [49]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '18thcentury',
 '19',
 '1930s',
 '1940s',
 '1944',
 '1950',
 '1950s',
 '1960s',
 '1970s',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '70s',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academic',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'ad

In [51]:
# Getting the number of features
print(len(cv.get_feature_names()))

5000


## NOTE: But we have a problem here, words like 'love', 'loving', 'lover' etc. are very similar so it will be a big problem.

In [52]:
import nltk

In [53]:
from nltk.stem.porter import PorterStemmer

In [54]:
ps=PorterStemmer()

In [56]:
def stem(text):
    y=[]
    
    for i in text.split():
        y.append(ps.stem(i)) # ps.stem(i) will basically convert loving,lover,loved etc to love.
    return " ".join(y)

In [58]:
new['tags']=new['tags'].apply(lambda x:stem(x))

C:\Users\Newtan\AppData\Local\Temp/ipykernel_8252/415986065.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['tags']=new['tags'].apply(lambda x:stem(x))


In [59]:
cv = CountVectorizer(max_features=5000,stop_words='english') 
#we only select the top 5000 words 
# ignore the english stop worrds like are,is,the etc.

In [60]:
print( cv.fit_transform(new['tags']).toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [61]:
vectors.shape

(4806, 5000)

In [64]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult'

## COSINE Similarity

In [66]:
from sklearn.metrics.pairwise import cosine_similarity #distancce is inverse of similarity

In [68]:
similarity = cosine_similarity(vectors)

In [69]:
similarity

array([[1.        , 0.08858079, 0.05812382, ..., 0.02450715, 0.02739983,
        0.        ],
       [0.08858079, 1.        , 0.06350006, ..., 0.02677398, 0.        ,
        0.        ],
       [0.05812382, 0.06350006, 1.        , ..., 0.02635231, 0.        ,
        0.        ],
       ...,
       [0.02450715, 0.02677398, 0.02635231, ..., 1.        , 0.0745356 ,
        0.04774099],
       [0.02739983, 0.        , 0.        , ..., 0.0745356 , 1.        ,
        0.05337605],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05337605,
        1.        ]])

In [71]:
# This will give the similarity of the first movie wwith every other movie

similarity[0]

array([1.        , 0.08858079, 0.05812382, ..., 0.02450715, 0.02739983,
       0.        ])

##### The diagonal of this similarity matrix is 1

In [74]:
list(enumerate(similarity[0]))

# List will now become like a tuple

[(0, 0.9999999999999998),
 (1, 0.0885807893036239),
 (2, 0.058123819371909635),
 (3, 0.03874921291460643),
 (4, 0.2029385157727364),
 (5, 0.11510231387903269),
 (6, 0.019510570275964215),
 (7, 0.19391446622548786),
 (8, 0.06213697660012),
 (9, 0.07435223956449145),
 (10, 0.14097096860865022),
 (11, 0.07897471897389846),
 (12, 0.0949157995752499),
 (13, 0.04649905549752771),
 (14, 0.13699915608779772),
 (15, 0.04956815970966097),
 (16, 0.10529962529853128),
 (17, 0.1461508458653816),
 (18, 0.13065106689280268),
 (19, 0.08561170049453902),
 (20, 0.056573571480353566),
 (21, 0.09320546490018),
 (22, 0.0685591170191061),
 (23, 0.09320546490018),
 (24, 0.05479966243511909),
 (25, 0.037229039552497),
 (26, 0.1891891891891892),
 (27, 0.20518233866439894),
 (28, 0.15007505629691606),
 (29, 0.06906138832741962),
 (30, 0.07118684968143743),
 (31, 0.18641092980036),
 (32, 0.08867021970429453),
 (33, 0.13151918984428584),
 (34, 0.0),
 (35, 0.14349920066683505),
 (36, 0.213352298825066),
 (37, 0.08

In [82]:
sorted(list(enumerate(similarity[0])),key=lambda x:x[1],reverse=True)

[(0, 0.9999999999999998),
 (1194, 0.28039985489311264),
 (539, 0.27788500718836423),
 (507, 0.26601065911288363),
 (1216, 0.2585054483469678),
 (582, 0.25834126576556143),
 (1920, 0.2567480829815484),
 (260, 0.24854790640048),
 (4405, 0.24659848095803594),
 (61, 0.24534987303147354),
 (4192, 0.24534987303147354),
 (74, 0.2450715406979359),
 (322, 0.24324324324324326),
 (495, 0.23995690956687132),
 (3608, 0.23745309047699004),
 (83, 0.2372894989381248),
 (1204, 0.2369241569216954),
 (972, 0.23621543814299706),
 (466, 0.23490461932490855),
 (1329, 0.23490461932490855),
 (2409, 0.23394386020951635),
 (3730, 0.2324952774876386),
 (2333, 0.23249527748763854),
 (47, 0.22966561493131393),
 (1444, 0.2279803762937766),
 (2999, 0.2279803762937766),
 (2971, 0.22581937608857244),
 (1201, 0.22568905807670636),
 (2204, 0.22555354977384034),
 (973, 0.22230800575069137),
 (1275, 0.22147019900891643),
 (461, 0.22056438662814232),
 (3327, 0.22056438662814232),
 (2786, 0.21747941810042),
 (931, 0.2136968

In [83]:
sorted(list(enumerate(similarity[0])),key=lambda x:x[1],reverse=True)[0:6]

[(0, 0.9999999999999998),
 (1194, 0.28039985489311264),
 (539, 0.27788500718836423),
 (507, 0.26601065911288363),
 (1216, 0.2585054483469678),
 (582, 0.25834126576556143)]

In [86]:
def recommend(movie):
    index = new[new['title'] == movie].index[0] # given the movie name, we get the index.
    distances=similarity[0]
    movies_list=sorted(list(enumerate(distances)),key=lambda x:x[1],reverse=True)[1:6]
    for i in movies_list:
         print(new.iloc[i[0]].title)
        
        

In [87]:
recommend('Avatar')

Small Soldiers
Titan A.E.
Independence Day
Aliens vs Predator: Requiem
Battle: Los Angeles
